---
- name: Manage Kiosk Configuration
  hosts: all
  become: yes
  vars:
    new_url: "https://www.pointclickcare.com/poc/userLogin.xhtml"
  tasks:
    - name: Update the KIOSK_URL in the kiosk.env file
      ansible.builtin.lineinfile:
        path: /etc/kiosk.env
        regexp: '^KIOSK_URL='
        line: 'KIOSK_URL="{{ new_url }}"'
    - name: Reboot the system
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after updating kiosk.env"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30